/**
 * Keyboard Plate - Generated by KLE-NG
 *
 * Cutout type: cherry-mx-basic
 * Stabilizer type: mx-basic
 * Plate thickness: 1.5 mm
 * Generated: 2026-09-06
 *
 * This file uses the @jscad/modeling API (OpenJSCAD v2).
 * Open with: https://openjscad.xyz/
 */
const jscad = require('@jscad/modeling')
const { polygon, roundedRectangle } = jscad.primitives
const { rotateZ, translate } = jscad.transforms
const { extrudeLinear } = jscad.extrusions
const { subtract, union } = jscad.booleans

const THICKNESS = 1.5 // mm

// --- Plate outline ---
const outline_0 = polygon({ points: [
  [-15.5, 17], [-16.074, 16.886], [-16.561, 16.561], [-16.886, 16.074],
  [-17, 15.5], [-17, -0.549], [-17.115, -1.125], [-17.44, -1.61],
  [-17.925, -1.935], [-18.501, -2.05], [-44.074, -2.05], [-44.65, -2.164],
  [-45.135, -2.488], [-45.46, -2.976], [-45.575, -3.55], [-45.575, -91.7],
  [-45.46, -92.274], [-45.135, -92.761], [-44.65, -93.086], [-44.074, -93.199],
  [75.527, -93.199], [55.938, -127.13], [55.749, -127.686], [55.788, -128.27],
  [56.047, -128.792], [56.488, -129.179], [71.686, -137.954], [84.634, -145.43],
  [88.183, -147.478], [101.129, -154.954], [116.329, -163.729], [116.883, -163.918],
  [117.467, -163.879], [117.991, -163.62], [118.378, -163.18], [136.679, -131.484],
  [144.153, -118.536], [152.928, -103.338], [153.115, -102.785], [153.078, -102.201],
  [152.819, -101.674], [152.379, -101.29], [113, -78.552], [112.601, -78.217],
  [112.34, -77.767], [112.249, -77.255], [112.249, 15.5], [112.136, 16.074],
  [111.811, 16.561], [111.324, 16.886], [110.75, 17]
] })
const outline_1 = polygon({ points: [
  [232.151, 17], [231.577, 16.886], [231.089, 16.561], [230.765, 16.074],
  [230.649, 15.5], [230.649, -77.255], [230.561, -77.767], [230.3, -78.217],
  [229.901, -78.552], [190.522, -101.29], [190.082, -101.674], [189.823, -102.201],
  [189.783, -102.785], [189.973, -103.338], [198.748, -118.536], [206.222, -131.484],
  [224.523, -163.18], [224.907, -163.62], [225.434, -163.879], [226.018, -163.918],
  [226.571, -163.729], [241.769, -154.954], [254.717, -147.478], [258.267, -145.43],
  [271.215, -137.954], [286.413, -129.179], [286.853, -128.792], [287.112, -128.27],
  [287.149, -127.686], [286.962, -127.13], [267.371, -93.199], [386.975, -93.199],
  [387.548, -93.086], [388.036, -92.761], [388.361, -92.274], [388.476, -91.7],
  [388.476, -3.55], [388.361, -2.976], [388.036, -2.488], [387.548, -2.164],
  [386.975, -2.05], [361.399, -2.05], [360.826, -1.935], [360.338, -1.61],
  [360.013, -1.125], [359.9, -0.549], [359.9, 15.5], [359.787, 16.074],
  [359.462, 16.561], [358.975, 16.886], [358.401, 17]
] })
const outline = union(outline_0, outline_1)

// --- Shared shapes ---
const switch_shape = roundedRectangle({ size: [14, 14], roundRadius: 0.4 })
const stab_pad = roundedRectangle({ size: [7, 15], roundRadius: 0.5 })

// --- Switch cutouts ---
const switch_0 = switch_shape  // "0,1" 1u
const switch_1 = translate([19.05, 0, 0], switch_shape)  // "0,2" 1u
const switch_2 = translate([38.1, 0, 0], switch_shape)  // "0,3" 1u
const switch_3 = translate([57.15, 0, 0], switch_shape)  // "0,4" 1u
const switch_4 = translate([76.2, 0, 0], switch_shape)  // "0,5" 1u
const switch_5 = translate([95.25, 0, 0], switch_shape)  // "0,6" 1u
const switch_6 = translate([247.65, 0, 0], switch_shape)  // "0,9" 1u
const switch_7 = translate([266.7, 0, 0], switch_shape)  // "0,10" 1u
const switch_8 = translate([285.75, 0, 0], switch_shape)  // "0,11" 1u
const switch_9 = translate([304.8, 0, 0], switch_shape)  // "0,12" 1u
const switch_10 = translate([323.85, 0, 0], switch_shape)  // "0,13" 1u
const switch_11 = translate([342.9, 0, 0], switch_shape)  // "0,14" 1u
const switch_12 = translate([-23.812, -19.05, 0], switch_shape)  // "1,0" 1.5u
const switch_13 = translate([0, -19.05, 0], switch_shape)  // "1,1" 1u
const switch_14 = translate([19.05, -19.05, 0], switch_shape)  // "1,2" 1u
const switch_15 = translate([38.1, -19.05, 0], switch_shape)  // "1,3" 1u
const switch_16 = translate([57.15, -19.05, 0], switch_shape)  // "1,4" 1u
const switch_17 = translate([76.2, -19.05, 0], switch_shape)  // "1,5" 1u
const switch_18 = translate([95.25, -19.05, 0], switch_shape)  // "1,6" 1u
const switch_19 = translate([247.65, -19.05, 0], switch_shape)  // "1,9" 1u
const switch_20 = translate([266.7, -19.05, 0], switch_shape)  // "1,10" 1u
const switch_21 = translate([285.75, -19.05, 0], switch_shape)  // "1,11" 1u
const switch_22 = translate([304.8, -19.05, 0], switch_shape)  // "1,12" 1u
const switch_23 = translate([323.85, -19.05, 0], switch_shape)  // "1,13" 1u
const switch_24 = translate([342.9, -19.05, 0], switch_shape)  // "1,14" 1u
const switch_25 = translate([366.713, -19.05, 0], switch_shape)  // "1,15" 1.5u
const switch_26 = translate([-23.812, -38.1, 0], switch_shape)  // "2,0" 1.5u
const switch_27 = translate([0, -38.1, 0], switch_shape)  // "2,1" 1u
const switch_28 = translate([19.05, -38.1, 0], switch_shape)  // "2,2" 1u
const switch_29 = translate([38.1, -38.1, 0], switch_shape)  // "2,3" 1u
const switch_30 = translate([57.15, -38.1, 0], switch_shape)  // "2,4" 1u
const switch_31 = translate([76.2, -38.1, 0], switch_shape)  // "2,5" 1u
const switch_32 = translate([95.25, -38.1, 0], switch_shape)  // "2,6" 1u
const switch_33 = translate([247.65, -38.1, 0], switch_shape)  // "2,9" 1u
const switch_34 = translate([266.7, -38.1, 0], switch_shape)  // "2,10" 1u
const switch_35 = translate([285.75, -38.1, 0], switch_shape)  // "2,11" 1u
const switch_36 = translate([304.8, -38.1, 0], switch_shape)  // "2,12" 1u
const switch_37 = translate([323.85, -38.1, 0], switch_shape)  // "2,13" 1u
const switch_38 = translate([342.9, -38.1, 0], switch_shape)  // "2,14" 1u
const switch_39 = translate([366.713, -38.1, 0], switch_shape)  // "2,15" 1.5u
const switch_40 = translate([-23.812, -57.15, 0], switch_shape)  // "3,0" 1.5u
const switch_41 = translate([0, -57.15, 0], switch_shape)  // "3,1" 1u
const switch_42 = translate([19.05, -57.15, 0], switch_shape)  // "3,2" 1u
const switch_43 = translate([38.1, -57.15, 0], switch_shape)  // "3,3" 1u
const switch_44 = translate([57.15, -57.15, 0], switch_shape)  // "3,4" 1u
const switch_45 = translate([76.2, -57.15, 0], switch_shape)  // "3,5" 1u
const switch_46 = translate([95.25, -57.15, 0], switch_shape)  // "3,6" 1u
const switch_47 = translate([247.65, -57.15, 0], switch_shape)  // "3,9" 1u
const switch_48 = translate([266.7, -57.15, 0], switch_shape)  // "3,10" 1u
const switch_49 = translate([285.75, -57.15, 0], switch_shape)  // "3,11" 1u
const switch_50 = translate([304.8, -57.15, 0], switch_shape)  // "3,12" 1u
const switch_51 = translate([323.85, -57.15, 0], switch_shape)  // "3,13" 1u
const switch_52 = translate([342.9, -57.15, 0], switch_shape)  // "3,14" 1u
const switch_53 = translate([366.713, -57.15, 0], switch_shape)  // "3,15" 1.5u
const switch_54 = translate([-23.812, -76.2, 0], switch_shape)  // "4,0" 1.5u
const switch_55 = translate([0, -76.2, 0], switch_shape)  // "4,1" 1u
const switch_56 = translate([19.05, -76.2, 0], switch_shape)  // "4,2" 1u
const switch_57 = translate([38.1, -76.2, 0], switch_shape)  // "4,3" 1u
const switch_58 = translate([57.15, -76.2, 0], switch_shape)  // "4,4" 1u
const switch_59 = translate([76.2, -76.2, 0], switch_shape)  // "4,5" 1u
const switch_60 = translate([95.25, -76.2, 0], switch_shape)  // "4,6" 1u
const switch_61 = translate([247.65, -76.2, 0], switch_shape)  // "4,9" 1u
const switch_62 = translate([266.7, -76.2, 0], switch_shape)  // "4,10" 1u
const switch_63 = translate([285.75, -76.2, 0], switch_shape)  // "4,11" 1u
const switch_64 = translate([304.8, -76.2, 0], switch_shape)  // "4,12" 1u
const switch_65 = translate([323.85, -76.2, 0], switch_shape)  // "4,13" 1u
const switch_66 = translate([342.9, -76.2, 0], switch_shape)  // "4,14" 1u
const switch_67 = translate([366.713, -76.2, 0], switch_shape)  // "4,15" 1.5u
const switch_68 = translate([122.207, -103.499, 0], rotateZ(-0.524, switch_shape))  // "5,7" 2u
const switch_69 = translate([220.693, -103.499, 0], rotateZ(0.524, switch_shape))  // "5,8" 2u
const switch_70 = translate([83.173, -113.958, 0], rotateZ(-0.524, switch_shape))  // "5,5" 1u
const switch_71 = translate([99.671, -123.483, 0], rotateZ(-0.524, switch_shape))  // "6,6" 1u
const switch_72 = translate([116.168, -133.008, 0], rotateZ(-0.524, switch_shape))  // "6,7" 1u
const switch_73 = translate([226.732, -133.008, 0], rotateZ(0.524, switch_shape))  // "6,8" 1u
const switch_74 = translate([243.229, -123.483, 0], rotateZ(0.524, switch_shape))  // "6,9" 1u
const switch_75 = translate([259.727, -113.958, 0], rotateZ(0.524, switch_shape))  // "5,10" 1u

// --- Stabilizer cutouts ---
const stab_68_a = translate([111.118, -98.829, 0], rotateZ(-0.524, stab_pad))
const stab_68_b = translate([131.796, -110.767, 0], rotateZ(-0.524, stab_pad))
const stab_68 = union(stab_68_a, stab_68_b)  // stabilizer for "5,7" (switch 68)
const stab_69_a = translate([211.104, -110.767, 0], rotateZ(0.524, stab_pad))
const stab_69_b = translate([231.782, -98.829, 0], rotateZ(0.524, stab_pad))
const stab_69 = union(stab_69_a, stab_69_b)  // stabilizer for "5,8" (switch 69)
const stab_70_a = translate([87.843, -102.869, 0], rotateZ(-2.094, stab_pad))
const stab_70_b = translate([75.905, -123.547, 0], rotateZ(-2.094, stab_pad))
const stab_70 = union(stab_70_a, stab_70_b)  // stabilizer for "5,5" (switch 70)
const stab_71_a = translate([104.341, -112.394, 0], rotateZ(-2.094, stab_pad))
const stab_71_b = translate([92.403, -133.072, 0], rotateZ(-2.094, stab_pad))
const stab_71 = union(stab_71_a, stab_71_b)  // stabilizer for "6,6" (switch 71)
const stab_72_a = translate([120.838, -121.919, 0], rotateZ(-2.094, stab_pad))
const stab_72_b = translate([108.9, -142.597, 0], rotateZ(-2.094, stab_pad))
const stab_72 = union(stab_72_a, stab_72_b)  // stabilizer for "6,7" (switch 72)
const stab_73_a = translate([219.464, -123.419, 0], rotateZ(-1.047, stab_pad))
const stab_73_b = translate([231.402, -144.097, 0], rotateZ(-1.047, stab_pad))
const stab_73 = union(stab_73_a, stab_73_b)  // stabilizer for "6,8" (switch 73)
const stab_74_a = translate([235.961, -113.894, 0], rotateZ(-1.047, stab_pad))
const stab_74_b = translate([247.899, -134.572, 0], rotateZ(-1.047, stab_pad))
const stab_74 = union(stab_74_a, stab_74_b)  // stabilizer for "6,9" (switch 74)
const stab_75_a = translate([252.459, -104.369, 0], rotateZ(-1.047, stab_pad))
const stab_75_b = translate([264.397, -125.047, 0], rotateZ(-1.047, stab_pad))
const stab_75 = union(stab_75_a, stab_75_b)  // stabilizer for "5,10" (switch 75)

// --- Assembly ---
const allCutouts = union(
  switch_0,
  switch_1,
  switch_2,
  switch_3,
  switch_4,
  switch_5,
  switch_6,
  switch_7,
  switch_8,
  switch_9,
  switch_10,
  switch_11,
  switch_12,
  switch_13,
  switch_14,
  switch_15,
  switch_16,
  switch_17,
  switch_18,
  switch_19,
  switch_20,
  switch_21,
  switch_22,
  switch_23,
  switch_24,
  switch_25,
  switch_26,
  switch_27,
  switch_28,
  switch_29,
  switch_30,
  switch_31,
  switch_32,
  switch_33,
  switch_34,
  switch_35,
  switch_36,
  switch_37,
  switch_38,
  switch_39,
  switch_40,
  switch_41,
  switch_42,
  switch_43,
  switch_44,
  switch_45,
  switch_46,
  switch_47,
  switch_48,
  switch_49,
  switch_50,
  switch_51,
  switch_52,
  switch_53,
  switch_54,
  switch_55,
  switch_56,
  switch_57,
  switch_58,
  switch_59,
  switch_60,
  switch_61,
  switch_62,
  switch_63,
  switch_64,
  switch_65,
  switch_66,
  switch_67,
  switch_68,
  stab_68,
  switch_69,
  stab_69,
  switch_70,
  stab_70,
  switch_71,
  stab_71,
  switch_72,
  stab_72,
  switch_73,
  stab_73,
  switch_74,
  stab_74,
  switch_75,
  stab_75
)
const plate2d = subtract(outline, allCutouts)
const plate3d = extrudeLinear({ height: THICKNESS }, plate2d)
const finalPlate = plate3d

const main = () => finalPlate

module.exports = { main }